net:
  port: 10201
  bindIp: 0.0.0.0
storage:
  dbPath: "/var/lib/mongodb/archive"
  directoryPerDB: true
  wiredTiger:
    engineConfig:
        cacheSizeGB: 2
systemLog:
  logAppend: true
  logRotate: reopen
  destination: file
  path: "/var/log/mongodb/archive.log"
replication:
  replSetName: "archive"
# Disable FTDC to avoid crashes
setParameter:
  diagnosticDataCollectionEnabled: false
