package com.sap.sailing.domain.persistence;


public enum FieldNames {
    // general:
    TIME_AS_MILLIS, KNOT_SPEED, DEGREE_BEARING, LAT_DEG, LNG_DEG, TRUE_HEADING_DEG,
    
    FLEET, RACE_IDENTIFIERS,
    
    /**
     * TODO this will have to be renamed to REGATTA_NAME, but compatibility concerns keep us from doing so at the moment
     */
    EVENT_NAME,
    EVENT_DESCRIPTION,
    EVENT_ID,
    EVENT_IS_PUBLIC,
    EVENT_START_DATE,
    EVENT_END_DATE,
    EVENT_IMAGE_URLS,
    EVENT_VIDEO_URLS,
    EVENT_SPONSOR_IMAGE_URLS,
    EVENT_IMAGES,
    EVENT_VIDEOS,
    EVENT_OFFICIAL_WEBSITE_URL,
    EVENT_BASE_URL,
    EVENT_SAILORS_INFO_WEBSITE_URL,
    EVENT_SAILORS_INFO_WEBSITES,
    EVENT_LOGO_IMAGE_URL,
    EVENT_WINDFINDER_SPOT_COLLECTION_IDS,
    
    REGATTA_NAME,
    REGATTA_ID,
    REGATTA_BASE_NAME,
    REGATTA_START_DATE,
    REGATTA_END_DATE,
    REGATTA_SERIES,
    REGATTA_REGATTA_CONFIGURATION,
    REGATTA_BUOY_ZONE_RADIUS_IN_HULL_LENGTHS,
    REGATTA_USE_START_TIME_INFERENCE,
    REGATTA_CONTROL_TRACKING_FROM_START_AND_FINISH_TIMES,
    REGATTA_AUTO_RESTART_TRACKING_UPON_COMPETITOR_SET_CHANGE,
    REGATTA_CAN_BOATS_OF_COMPETITORS_CHANGE_PER_RACE,
    REGATTA_COMPETITOR_REGISTRATION_TYPE,
    REGATTA_REGISTRATION_LINK_SECRET,
    SERIES_NAME,
    SERIES_IS_MEDAL,
    SERIES_IS_FLEETS_CAN_RUN_IN_PARALLEL,
    SERIES_MAXIMUM_NUMBER_OF_DISCARDS,
    SERIES_STARTS_WITH_ZERO_SCORE,
    SERIES_HAS_SPLIT_FLEET_CONTIGUOUS_SCORING,
    SERIES_HAS_CROSS_FLEET_MERGED_RANKING,
    SERIES_STARTS_WITH_NON_DISCARDABLE_CARRY_FORWARD,
    SERIES_ONE_ALWAYS_STAYS_ONE,
    SERIES_FLEETS,
    SERIES_RACE_COLUMNS,
    SERIES_DISCARDING_THRESHOLDS,
    FLEET_NAME,
    FLEET_ORDERING,
    FLEET_COLOR,
    
    SCORING_SCHEME_TYPE,
    
    RACE_NAME,
    RACE_ID,
    
    VENUE,
    VENUE_NAME,

    COURSE_AREAS,
    COURSE_AREA_NAME,
    COURSE_AREA_ID,
    COURSE_AREA_CENTER_POSITION,
    COURSE_AREA_RADIUS_IN_METERS,
    COURSE_AREA_IDS,
    
    BOAT_CLASS_NAME,
    BOAT_CLASS_TYPICALLY_STARTS_UPWIND,
    
    // wind:
    WIND_SOURCES_TO_EXCLUDE, WIND_SOURCE_NAME, WIND_SOURCE_ID, WIND, IS_MAGNETIC,
    
    // SwissTiming configuration parameters:
    ST_CONFIG_NAME, ST_CONFIG_HOSTNAME, ST_CONFIG_PORT,

    COMPETITOR, COMPETITOR_ID, COMPETITOR_DISPLAY_NAME, COMPETITOR_SHORT_NAME, COMPETITOR_BOAT_NAME, COMPETITOR_BOAT_SAIL_ID,
    
    // leaderboard:
    LEADERBOARD_NAME, LEADERBOARD_DISPLAY_NAME, LEADERBOARD_SUPPRESSED_COMPETITORS, LEADERBOARD_SUPPRESSED_COMPETITOR_IDS,
    LEADERBOARD_COLUMNS, LEADERBOARD_COLUMN_NAME, LEADERBOARD_COMPETITOR_DISPLAY_NAMES,
    LEADERBOARD_IS_MEDAL_RACE_COLUMN, LEADERBOARD_CARRIED_POINTS, LEADERBOARD_CARRIED_POINTS_BY_ID,
    LEADERBOARD_SCORE_CORRECTIONS, LEADERBOARD_DISCARDING_THRESHOLDS,
    LEADERBOARD_SCORE_CORRECTION_MAX_POINTS_REASON, LEADERBOARD_CORRECTED_SCORE,
    LEADERBOARD_INCREMENTAL_SCORE_CORRECTION_IN_POINTS, LEADERBOARD_SCORE_CORRECTION_TIMESTAMP,
    LEADERBOARD_RANK, LEADERBOARD_SCORE_CORRECTION_COMMENT, LEADERBOARD_SCORE_CORRECTION_MERGE_STATE,
    LEADERBOARD_COLUMN_FACTORS, WRAPPED_REGATTA_LEADERBOARD_NAME, OTHER_TIEBREAKING_LEADERBOARD_NAME,
    ELMINATED_COMPETITORS,

    // leaderboard group
    LEADERBOARD_GROUP_UUID, LEADERBOARD_GROUP_NAME, LEADERBOARD_GROUP_DESCRIPTION,
    LEADERBOARD_GROUP_DISPLAY_NAME, LEADERBOARD_GROUP_LEADERBOARDS, LEADERBOARD_GROUP_OVERALL_LEADERBOARD,
    LEADERBOARD_GROUP_DISPLAY_IN_REVERSE_ORDER,
    
    // race ID to regatta name
    RACE_ID_AS_STRING,
    
    // race log
    RACE_LOG_IDENTIFIER, RACE_LOG_EVENT, RACE_LOG_EVENT_PASS_ID, RACE_LOG_EVENT_ID, RACE_LOG_EVENT_CREATED_AT, RACE_LOG_EVENT_AUTHOR_NAME,
    RACE_LOG_EVENT_AUTHOR_PRIORITY, RACE_LOG_EVENT_INVOLVED_BOATS, RACE_LOG_EVENT_FLAG_UPPER, RACE_LOG_EVENT_FLAG_LOWER, RACE_LOG_EVENT_FLAG_DISPLAYED,
    RACE_LOG_EVENT_START_TIME, RACE_LOG_EVENT_COURSE_AREA_ID_AS_STRING, RACE_LOG_EVENT_CLASS, RACE_LOG_EVENT_NEXT_STATUS, RACE_LOG_COURSE_DESIGN, RACE_LOG_COURSE_DESIGNER_MODE, WAYPOINT_ID, WAYPOINT_NAME,
    WAYPOINT_PASSINGINSTRUCTIONS, CONTROLPOINT, CONTROLPOINT_CLASS, MARK_ID, MARK_COLOR, MARK_NAME, MARK_SHORT_NAME, MARK_PATTERN, MARK_SHAPE, MARK_TYPE,
    MARK_ORIGINATING_MARK_TEMPLATE_ID, MARK_ORIGINATING_MARK_PROPERTIES_ID, RACE_LOG_COURSE_ORIGINATING_TEMPLATE_ID, RACE_LOG_COURSE_ASSOCIATED_ROLES, RACE_LOG_COURSE_ASSOCIATED_ROLES_MARK_ID, RACE_LOG_COURSE_ASSOCIATED_ROLES_ROLE_ID,
    CONTROLPOINT_VALUE, CONTROLPOINTWITHTWOMARKS_ID, CONTROLPOINTWITHTWOMARKS_NAME, CONTROLPOINTWITHTWOMARKS_SHORT_NAME, CONTROLPOINTWITHTWOMARKS_LEFT, CONTROLPOINTWITHTWOMARKS_RIGHT,
    RACE_LOG_POSITIONED_COMPETITORS, RACE_LOG_PATHFINDER_ID, RACE_LOG_GATE_LINE_OPENING_TIME, RACE_LOG_GOLF_DOWN_TIME, RACE_LOG_START_PROCEDURE_TYPE,
    RACE_LOG_PROTEST_START_TIME, RACE_LOG_PROTEST_END_TIME, RACE_LOG_COURSE_DESIGN_NAME, RACE_LOG_REVOKED_EVENT_ID, RACE_LOG_REVOKED_EVENT_TYPE, 
    RACE_LOG_REVOKED_EVENT_SHORT_INFO, RACE_LOG_REVOKED_REASON, RACE_LOG_DEVICE_MAPPING_EVENT_ID,
    RACE_LOG_CLOSING_TIMEPOINT, TIMEPOINT_OF_FIXED_MARKPASSING, INDEX_OF_PASSED_WAYPOINT,INDEX_OF_FIRST_SUPPRESSED_WAYPOINT, MARK, RACE_LOG_COMPETITOR_ID, RACE_LOG_BOAT_ID, 
    RACE_LOG_DEPDENDENT_ON_FLEET, RACE_LOG_DEPDENDENT_ON_RACECOLUMN, RACE_LOG_DEPDENDENT_ON_REGATTALIKE,
    RACE_LOG_START_TIME_DIFFERENCE_IN_MS, RACE_LOG_FINISHING_TIME_AS_MILLIS, RACE_LOG_TAG, RACE_LOG_COMMENT, RACE_LOG_HIDDEN_INFO, RACE_LOG_IMAGE_URL, RACE_LOG_RESIZED_IMAGE_URL, 
    /** @deprecated Replaced by {@link #REGATTA_LOG_FROM}; auto-migration from race log device mappings to regatta log is implemented */ @Deprecated RACE_LOG_FROM,
    /** @deprecated Replaced by {@link #REGATTA_LOG_TO}; auto-migration from race log device mappings to regatta log is implemented */ @Deprecated RACE_LOG_TO,
    /** @deprecated Replaced by a regatta log entry with type {@link #REGATTA_LOG_MARK} */ @Deprecated RACE_LOG_MARK,
    /** @deprecated Replaced by WAYPOINT_PASSINGINSTRUCTIONS, still used to migrate old races*/ @Deprecated WAYPOINT_PASSINGSIDE,
    /** @deprecated Replaced by CONTROLPOINTWITHTWOMARKS_ID, still used to migrate old races*/ @Deprecated GATE_ID,
    /** @deprecated Replaced by CONTROLPOINTWITHTWOMARKS_NAME, still used to migrate old races*/ @Deprecated GATE_NAME,
    /** @deprecated Replaced by CONTROLPOINTWITHTWOMARKS_LEFT, still used to migrate old races*/ @Deprecated GATE_LEFT,
    /** @deprecated Replaced by CONTROLPOINTWITHTWOMARKS_RIGHT, still used to migrate old races*/ @Deprecated GATE_RIGHT,

   //ORC Leg fields
    ORC_LEG_NR, ORC_LEG_LENGTH_IN_NAUTICAL_MILES, ORC_LEG_TWA_IN_DEG, ORC_LEG_TYPE,

    // regatta log
    // did not reuse RACE_LOG* types, as this would require handling old versions of all events
    REGATTA_LOG_IDENTIFIER_TYPE, REGATTA_LOG_IDENTIFIER_NAME, REGATTA_LOG_EVENT_ID, REGATTA_LOG_EVENT_CREATED_AT, REGATTA_LOG_EVENT_AUTHOR_NAME,
    REGATTA_LOG_EVENT_AUTHOR_PRIORITY, REGATTA_LOG_EVENT_CLASS, REGATTA_LOG_REVOKED_EVENT_ID, REGATTA_LOG_REVOKED_EVENT_TYPE, REGATTA_LOG_REVOKED_EVENT_SHORT_INFO,
    REGATTA_LOG_REVOKED_REASON, REGATTA_LOG_COMPETITOR_ID, REGATTA_LOG_BOAT_ID, REGATTA_LOG_DEVICE_MAPPING_EVENT_ID, REGATTA_LOG_CLOSING_TIMEPOINT,
    REGATTA_LOG_FROM, REGATTA_LOG_TO, REGATTA_LOG_EVENT, REGATTA_LOG_MARK,
    
    // remote server reference fields
    SERVER_NAME,
    SERVER_URL,
    INCLUDE,
    SELECTED_EVENT_IDS,
    
    // local server instance fields
    SERVER_IS_STANDALONE,
    
    // configurations
    CONFIGURATION_ID_AS_STRING, CONFIGURATION_NAME, @Deprecated CONFIGURATION_MATCHER, CONFIGURATION_CONFIG,
    @Deprecated CONFIGURATION_MATCHER_ID, @Deprecated CONFIGURATION_MATCHER_CLIENTS, 
    CONFIGURATION_CONFIG_ALLOWED_COURSE_AREA_NAMES, CONFIGURATION_CONFIG_MIN_ROUNDS, CONFIGURATION_CONFIG_MAX_ROUNDS, CONFIGURATION_CONFIG_RESULTS_MAIL,
    CONFIGURATION_CONFIG_PROCEDURES,
    
    // GPSFixes
    DEVICE_ID, GPSFIX_TYPE, GPSFIX,
    
    // GPSFixes metadata
    TIMERANGE, NUM_FIXES, LAST_FIX_RECEIVED,
    
    // Timespan
    FROM_MILLIS, TO_MILLIS,

    // Result Import url fields
    RESULT_PROVIDERNAME, RESULT_URL, 
    
    // type of additional scoring information
    RACE_LOG_ADDITIONAL_SCORING_INFORMATION_TYPE,
    
    // Handicap factors
    REGATTA_LOG_TIME_ON_TIME_FACTOR, REGATTA_LOG_TIME_ON_DISTANCE_SECONDS_ALLOWANCE_PER_NAUTICAL_MILE, REGATTA_RANKING_METRIC, REGATTA_RANKING_METRIC_TYPE,
    
    // image fields
    IMAGE_URL, IMAGE_LOCALE, IMAGE_TITLE, IMAGE_SUBTITLE, IMAGE_MIMETYPE, IMAGE_COPYRIGHT, IMAGE_CREATEDATDATE, 
    IMAGE_WIDTH_IN_PX, IMAGE_HEIGHT_IN_PX, IMAGE_TAGS,
    
    // video fields
    VIDEO_URL, VIDEO_LOCALE, VIDEO_TITLE, VIDEO_SUBTITLE, VIDEO_MIMETYPE, VIDEO_COPYRIGHT, VIDEO_CREATEDATDATE, 
    VIDEO_TAGS, VIDEO_THUMBNAIL_URL, VIDEO_LENGTH_IN_SECONDS,
    
    // sailors info fileds
    SAILORS_INFO_URL, SAILORS_INFO_LOCALE,
    
    // double vector fixes
    FIX,
    
    //anniversary fields
    START_OF_RACE, ANNIVERSARY_NUMBER, REMOTE_URL, ANNIVERSARY_TYPE, EVENT_TYPE,
    
    //ORC certificate fields,
    ORC_CERTIFICATE, ORC_CERTIFICATE_SAILNUMBER, ORC_CERTIFICATE_GPH, ORC_CERTIFICATE_CDL, ORC_CERTIFICATE_BEAT_ANGLES, ORC_CERTIFICATE_RUN_ANGLES,
    ORC_CERTIFICATE_BEAT_ALLOWANCES, ORC_CERTIFICATE_RUN_ALLOWANCES, ORC_CERTIFICATE_BEAT_VMG_PREDICTIONS, ORC_CERTIFICATE_RUN_VMG_PREDICTIONS,
    ORC_CERTIFICATE_TWS_6KT, ORC_CERTIFICATE_TWS_8KT, ORC_CERTIFICATE_TWS_10KT, ORC_CERTIFICATE_TWS_12KT,
    ORC_CERTIFICATE_TWS_14KT, ORC_CERTIFICATE_TWS_16KT, ORC_CERTIFICATE_TWS_20KT, ORC_CERTIFICATE_R52_PREDICTION, ORC_CERTIFICATE_R60_PREDICTION,
    ORC_CERTIFICATE_R75_PREDICTION, ORC_CERTIFICATE_R90_PREDICTION, ORC_CERTIFICATE_R110_PREDICTION, ORC_CERTIFICATE_R120_PREDICTION,
    ORC_CERTIFICATE_R135_PREDICTION, ORC_CERTIFICATE_R150_PREDICTION, ORC_CERTIFICATE_BOATCLASS, ORC_CERTIFICATE_LENGTH, ORC_CERTIFICATE_TWA_SPEED_PREDICTIONS,
    ORC_CERTIFICATE_CIRCULAR_RANDOM_SPEED_PREDICTIONS, ORC_CERTIFICATE_NON_SPINNAKER_SPEED_PREDICTIONS, ORC_OTHER_RACE_IDENTIFIER, ORC_IMPLIED_WIND_SOURCE,
    
    // MARKPASSINGS collection
    MARK_PASSINGS_FINGERPRINT, MARK_PASSINGS,
    
    // MANEUVERS collection:
    MANEUVER_FINGERPRINT, MANEUVERS, SIMPLE_CLASS_NAME, TYPE, TACK, POSITION_LAT_RAD, POSITION_LNG_RAD, TIMEPOINT, MAIN_CURVE_BOUNDARIES,
    MANEUVER_CURVE_WITH_STABLE_SPEED_AND_COURSE_BOUNDERIES, MAX_TURNING_RATE_IN_DEGREE_PER_SECOUND, MANEUVER_LOSS, 
    // MANEUVERS main curve boundaries properties, see MAIN_CURVE_BOUNDARIES field above
    MANEUVER_TIMEPOINT_BEFORE, MANEUVER_TIMEPOINT_AFTER, MANEUVER_SPEED_WITH_BEARING_BEFORE, MANEUVER_SPEED_WITH_BEARING_AFTER,
    MANEUVER_DIRECTION_CHANGE_IN_DEGREES, MANEUVER_LOWEST_SPEED_IN_KNOTS, MANEUVER_HIGHEST_SPEED_IN_KNOTS,
    MANEUVER_DISTANCE_SAILED_POMA, MANEUVER_DISTANCE_SAILED_INMPOMA, MANEUVER_SPEED_WITH_BEARING_BEFORE_DEGREES,
    MANEUVER_SPEED_WITH_BEARING_BEFORE_SPEED, MANEUVER_SPEED_WITH_BEARING_AFTER_DEGREES, MANEUVER_SPEED_WITH_BEARING_AFTER_SPEED_IN_KNOTS, 
    MANEUVER_START_POSITION_LAT_RAD, MANEUVER_START_POSITION_LNG_RAD, MANEUVER_END_POSITION_LAT_RAD,
    MANEUVER_END_POSITION_LNG_RAD, MIDDLE_MAEUVER_ANGLE, MANEUVER_LOSS_DURATION, MANEUVER_PAGE_INDEX
    ;
}
