package com.sap.sse.gwt.shared;

import java.util.Optional;

import com.google.gwt.core.client.GWT;
import com.sap.sse.branding.shared.BrandingConfiguration;
import com.sap.sse.gwt.client.context.data.ClientConfigurationContextDataJSO;
import com.sap.sse.gwt.client.context.impl.ClientConfigurationContextDataFactoryImpl;

/**
 * Provides information for the GWT client if debranding/whitelabeling is currently active or alternatively provides
 * string and image resources specific to the branding selected. Data is read from the static HTML page which starts the
 * GWT client code. Within the header you need to insert a script tag that installs an object with the necessary data
 * into the document object tree of the browser:
 * 
 * <pre>
 *   &lt;script&gt;${clientConfigurationContext['scriptForClientConfigurationContextToDocument']}&lt;/script&gt;
 * </pre>
 * 
 * The data in this structure is integrated into the document object tree within the browser. It looks like this:
 * 
 * <pre>
 *      document.clientConfigurationContext={"brandingActive":true,"brandTitle":"SAP ","debrandingActive":false,"whitelabeled":"",...};
 * </pre>
 * 
 * That can be accessed from here using the {@link ClientConfigurationContextDataJSO}. Responsible for the properties
 * listed in the object is {@link BrandingConfigurationService#getBrandingConfigurationProperties(Optional)} and its
 * {@link BrandingConfigurationService#getActiveBrandingConfiguration() active branding configuration}, or none if the
 * solution is running without any branding.
 * <p>
 * 
 * The structure in the HTML is generated by the server, see {@code com.sap.sse.branding.ClientConfigurationListener}
 * for that.
 * 
 * To add new fields the following steps must be performed:
 * <ul>
 * <li>{@code BrandingConfigurationProperty} must be extended with a new entry for the new field</li>
 * <li>{@link BrandingConfiguration} must be extended with a new method to access the new field</li>
 * <li>This forces an extension of all implementations of {@link BrandingConfiguration}, such as the specific branding
 * services, but also this {@link ClientConfiguration} class which also implements the {@link BrandingConfiguration}
 * interface</li>
 * <li>class {@link ClientConfigurationContextDataJSO} must be extended with an getter for the new field</li>
 * <li>corresponding variable filled with the appropriate value in
 * {@code BrandingConfigurationServiceImpl.getBrandingConfigurationProperties(Optional)}</li>
 * </ul>
 * <p>
 * 
 * Methods accepting an {@link Optional} locale parameter are used to support internationalization of the branding
 * information in the back-end. GWT clients can use {@link Optional#empty()} when using an instance of this class and
 * will get an internationalized value because the back-end will have handled the client's locale information.
 * 
 * @author Georg Herdt
 *
 */
public class ClientConfiguration implements BrandingConfiguration {

    private static final ClientConfiguration INSTANCE;

    static {
        INSTANCE = new ClientConfiguration();
    }

    public static ClientConfiguration getInstance() {
        return INSTANCE;
    }

    private boolean brandingActive = true;
    private String id;
    private String brandTitle;
    private String defaultBrandingLogoURL;
    private String greyTransparentLogoURL;
    private String solutionsInSailingImageURL;
    private String soutionsInSailingTrimmedImageURL;
    private String sailingRaceManagerAppTrimmedImageURL;
    private String sailInSightAppImageURL;
    private String sailingRaceManagerAppImageURL;
    private String sailingSimulatorImageURL;
    private String sailingSimulatorTrimmedImageURL;
    private String buoyPingerAppImageURL;
    private String sailingAnalyticsImageURL;
    private String sailingAnalyticsReadMoreText;
    private String sailingAnalyticsSailing;
    private String footerCopyright;
    private String footerPrivacyLink;
    private String footerJobsLink;
    private String footerSupportLink;
    private String sportsOn;
    private String followSports;
    private String facebookLink;
    private String xLink;
    private String instagramLink;
    private String welcomeToSailingAnalytics;
    private String welcomeToSailingAnalyticsBody;
    private String moreLoginInformationNotificationsURL;
    private String moreLoginInformationSettingsURL;
    private String moreLoginInformationSailorProfilesURL;
    private String moreLoginInformationSimulatorURL;
    private String inSailingContent;
    private String followGitHub;
    private String gitHubLink;

    public ClientConfiguration() {
        try {
            ClientConfigurationContextDataJSO dataJso = new ClientConfigurationContextDataFactoryImpl().getInstance();
            
            id = dataJso.getId();
            brandTitle = dataJso.getBrandTitle();
            defaultBrandingLogoURL = dataJso.getDefaultBrandingLogoURL();
            greyTransparentLogoURL = dataJso.getGreyTransparentLogoURL();
            solutionsInSailingImageURL = dataJso.getSoutionsInSailingImageURL();
            soutionsInSailingTrimmedImageURL = dataJso.getSolutionsInSailingTrimmedImageURL();
            sailingRaceManagerAppTrimmedImageURL = dataJso.getSailingRaceManagerAppTrimmedImageURL();
            sailInSightAppImageURL = dataJso.getSailInSightAppImageURL();
            brandingActive = !dataJso.isDebrandingActive();
            sailingRaceManagerAppImageURL = dataJso.getSailingRaceManagerAppImageURL();
            sailingSimulatorImageURL = dataJso.getSailingSimulatorImageURL();
            sailingSimulatorTrimmedImageURL = dataJso.getSailingSimulatorTrimmedImageURL();
            buoyPingerAppImageURL = dataJso.getBuoyPingerAppImageURL();
            sailingAnalyticsImageURL = dataJso.getSailingAnalyticsImageURL();
            sailingAnalyticsReadMoreText = dataJso.getSailingAnalyticsReadMoreText();
            sailingAnalyticsSailing = dataJso.getSailingAnalyticsSailing();
            footerCopyright = dataJso.getFooterCopyright();
            footerPrivacyLink = dataJso.getFooterPrivacyLink();
            footerJobsLink = dataJso.getFooterJobsLink();
            footerSupportLink = dataJso.getFooterSupportLink();
            sportsOn = dataJso.getSportsOn();
            followSports = dataJso.getFollowSports();
            xLink = dataJso.getxLink();
            facebookLink = dataJso.getFacebookLink();
            instagramLink = dataJso.getInstagramLink();
            welcomeToSailingAnalytics = dataJso.getWelcomeToSailingAnalytics();
            welcomeToSailingAnalyticsBody = dataJso.getWelcomeToSailingAnalyticsBody();
            moreLoginInformationNotificationsURL = dataJso.getMoreLoginInformationNotificationsURL();
            moreLoginInformationSettingsURL = dataJso.getMoreLoginInformationSettingsURL();
            moreLoginInformationSailorProfilesURL = dataJso.getMoreLoginInformationSailorProfilesURL();
            moreLoginInformationSimulatorURL = dataJso.getMoreLoginInformationSimulatorURL();
            gitHubLink = dataJso.getGitHubLink();
            followGitHub = dataJso.getFollowGitHub();
            

        } catch (RuntimeException e) {
            GWT.log("no branding information found.");
        }
    }

    @Override
    public String getId() {
        return id;
    }

    /**
     * Access whitelabeling information.
     * @return true when branding information shall be shown
     */
    public boolean isBrandingActive() {
        return brandingActive;
    }

    @Override
    public String getBrandTitle(Optional<String> locale) {
        return brandTitle;
    }

    @Override
    public String getDefaultBrandingLogoURL(Optional<String> locale) {
        return defaultBrandingLogoURL;
    }

    @Override
    public String getGreyTransparentLogoURL(Optional<String> locale) {
        return greyTransparentLogoURL;
    }

    @Override
    public String getSolutionsInSailingImageURL() {
        return solutionsInSailingImageURL;
    }

    @Override
    public String getSoutionsInSailingTrimmedImageURL() {
        return soutionsInSailingTrimmedImageURL;
    }

    @Override
    public String getSailingRaceManagerAppTrimmedImageURL() {
        return sailingRaceManagerAppTrimmedImageURL;
    }
    
    public String getSailInSightAppImageURL() {
        return sailInSightAppImageURL;
    }

    @Override
    public String getSailingRaceManagerAppImageURL() {
        return sailingRaceManagerAppImageURL;
    }

    @Override
    public String getSailingSimulatorImageURL() {
        return sailingSimulatorImageURL;
    }

    @Override
    public String getSailingSimulatorTrimmedImageURL() {
        return sailingSimulatorTrimmedImageURL;
    }

    public String getBuoyPingerAppImageURL() {
        return buoyPingerAppImageURL;
    }

    public String getSailingAnalyticsImageURL() {
        return sailingAnalyticsImageURL;
    }

    public String getSailingAnalyticsReadMoreText(Optional<String> locale) {
        return sailingAnalyticsReadMoreText;
    }
    public String getSailingAnalyticsSailing(Optional<String> locale) {
        return sailingAnalyticsSailing;
    }
    public String getFooterCopyright() {
        return footerCopyright;
    }
    public String getFooterPrivacyLink() {
        return footerPrivacyLink;
    }
    public String getFooterJobsLink() {
        return footerJobsLink;
    }
    public String getFooterSupportLink() {
        return footerSupportLink;
    }
    public String getSportsOn(Optional<String> locale) {
        return sportsOn;
    }
    public String getFollowSports(Optional<String> locale) {
        return followSports;
    }
    public String getFacebookLink() {
        return facebookLink;
    }
    public String getxLink() {
        return xLink;
    }
    public String getInstagramLink() {
        return instagramLink;
    }
    public String getWelcomeToSailingAnalytics(Optional<String> locale) {
        return welcomeToSailingAnalytics;
    }
    public String getWelcomeToSailingAnalyticsBody(Optional<String> locale) {
        return welcomeToSailingAnalyticsBody;
    }
    
    public String getMoreLoginInformationNotificationsURL() {
        return moreLoginInformationNotificationsURL;
    }

    public String getMoreLoginInformationSettingsURL() {
        return moreLoginInformationSettingsURL;
    }

    public String getMoreLoginInformationSailorProfilesURL() {
        return moreLoginInformationSailorProfilesURL;
    }

    public String getMoreLoginInformationSimulatorURL() {
        return moreLoginInformationSimulatorURL;
    }
    
    public String getInSailingContent(Optional<String> locale) {
        return inSailingContent;
    }
    
    public String getFollowGitHub(Optional<String> locale) {
        return followGitHub;
    }
    
    public String getGitHubLink() {
        return gitHubLink;
    }
}
