# Here you can define the log appenders
handlers= java.util.logging.FileHandler, java.util.logging.ConsoleHandler

# Assign the default log level
.level = INFO

# fileHandler specific properties
java.util.logging.FileHandler.level = ALL
java.util.logging.FileHandler.pattern = sailing_debug%u.log
java.util.logging.FileHandler.limit = 50000000
java.util.logging.FileHandler.count = 10
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter

# consoleHandler specific properties
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# Overwrite the log leves for specific loggers here
com.sap.sailing.level = INFO
com.sap.sse.level = INFO
#com.sap.sailing.domain.markpassingcalculation.level = FINEST
com.sap.sailing.domain.markpassingcalculation.level = INFO
# log at level FINEST for TransientCompetitorStoreIMpl
#com.sap.sailing.domain.base.impl.TransientCompetitorStoreImpl.level = FINEST
#com.sap.sailing.domain.base.impl.SharedDomainFactoryImpl.level = FINEST
# Want to see start time inference in detail:
#com.sap.sailing.domain.tracking.impl.TrackedRaceImpl.level = FINEST
#com.sap.sse.replication.impl.ReplicationReceiver.level = FINEST
#com.sap.sse.replication.impl.ReplicableWithObjectInputStream.level = FINEST
#com.sap.sailing.domain.tracking.impl.DynamicTrackedRaceImpl.level = FINER
#com.sap.sailing.domain.tracking.impl.DynamicGPSFixMovingTrackImpl.level = FINER
org.eclipse.jetty.level = INFO
org.apache.activemq.level = INFO

# TTCM logging is disabled by default; enable by commenting out the following line
com.sap.sailing.domain.tracking.impl.DynamicTrackImpl.level = OFF

# For debugging branch bug5611:
#com.sap.sse.replication.impl.ReplicationReceiverImpl.level = FINE

# For debugging branch bug5741:
#com.sap.sse.replication.impl.level = FINE

# JSch logging
com.sap.sse.landscape.aws.JCraftLogAdapter.level = ALL

# Parallel asynchronous replication queue processing, bug 5518:
com.sap.sse.replication.impl.OperationQueueByKeyExecutor.level = INFO

# YB logging
com.sap.sailing.domain.yellowbrickadapter.level = ALL

com.sap.sailing.domain.persistence.racelog.tracking.impl.MetadataCollection.level = FINE

#com.sap.sailing.windestimation.integration.IncrementalMstHmmWindEstimationForTrackedRace.level = FINE
#com.sap.sailing.windestimation.integration.IncrementalMstHmmWindEstimationForTrackedRace.GraphRecalculationTask.level = FINE

com.sap.sailing.domain.queclinkadapter.tracker.QueclinkTCPTracker.level = FINE
com.sap.sailing.domain.queclinkadapter.tracker.QueclinkUDPTracker.level = FINE

# Show locking progress in AIAgentImpl:
#com.sap.sailing.aiagent.impl.AIAgentImpl.level = FINE
# Show AI rules task enqueuing:
com.sap.sailing.aiagent.impl.RaceListener.level = FINE

# Show GithubReleasesRepository log output
com.sap.sse.landscape.impl.GithubReleasesRepository.level = FINE