name: build-jetty-p2

on:
  workflow_dispatch: {}

jobs:
  build-jetty-p2:
    permissions:
      contents: write
      checks: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Download Eclipse Platform Runtime
        run: |
          curl -fsSL \
            'https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.38-202512010920/eclipse-platform-4.38-linux-gtk-x86_64.tar.gz&r=1' \
            -o eclipse.tar.gz
          tar -xzf eclipse.tar.gz
      - name: Mirror Jetty p2 repository
        shell: bash
        run: |
          VERSION=$(
            curl -fsSL https://download.eclipse.org/jetty/updates/jetty-bundles-9.x/ \
            | grep "/jetty/updates/jetty-bundles-9.x" \
            | sed -e 's/^.*> \?\(9\.4\.[0-9]*\.v[0-9]*\)<.*$/\1/' \
            | sort -V \
            | tail -1
          )
          echo "Found version ${VERSION}"
          echo "VERSION=${VERSION}" >> "${GITHUB_ENV}"
          mkdir repository
          ./eclipse/eclipse \
            -nosplash \
            -verbose \
            -application org.eclipse.equinox.p2.metadata.repository.mirrorApplication \
            -source https://download.eclipse.org/jetty/updates/jetty-bundles-9.x/${VERSION}/ \
            -destination file:${PWD}/repository 2>&1 | tee build.log
          ./eclipse/eclipse \
            -nosplash \
            -verbose \
            -application org.eclipse.equinox.p2.artifact.repository.mirrorApplication \
            -source https://download.eclipse.org/jetty/updates/jetty-bundles-9.x/${VERSION}/ \
            -destination file:${PWD}/repository 2>&1 | tee -a build.log
      - name: Upload build log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build.log
          path: build.log
          retention-days: 90
      - name: Upload p2 site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jetty-p2
          path: repository/**/*
          retention-days: 90
      - name: SCP artifacts to download.eclipse.org to version-specific folder
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1
        with:
          host: projects-storage.eclipse.org
          username: ${{ secrets.SCP_USERNAME }}
          key: ${{ secrets.SCP_KEY }}
          passphrase: ${{ secrets.SCP_PASSPHRASE }}
          source: "repository"
          target: "/home/data/httpd/download.eclipse.org/sailing-analytics/p2/jetty-${{ env.VERSION }}"
          strip_components: 1
          rm: true
