name: build-jetty-p2

on:
  workflow_dispatch: {}

jobs:
  build-jetty-p2:
    permissions:
      contents: write
      checks: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          comment_on_pr: false
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 500
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Mirror Jetty p2 repository
        shell: bash
        run: |
          VERSION=$(
            curl -fsSL https://download.eclipse.org/jetty/updates/jetty-bundles-9.x/ \
            | grep "/jetty/updates/jetty-bundles-9.x" \
            | sed -n 's/^.*>\(9\.4\.[0-9]*\.v[0-9]*\)\/<.*$/\1/p' \
            | sort -V \
            | tail -1
          )
          echo "Found version ${VERSION}"
          echo "VERSION=${VERSION}" >> "${GITHUB_ENV}"
          mvn \
            org.eclipse.tycho:tycho-p2-repository-plugin:mirror \
            -Dsource=https://download.eclipse.org/jetty/updates/jetty-bundles-9.x/${VERSION}/ \
            -Ddestination=${GITHUB_WORKSPACE}/repository \
            2>&1 | tee build.log
      - name: Upload build log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build.log
          path: build.log
          retention-days: 90
      - name: Upload p2 site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jetty-p2
          path: repository/**/*
          retention-days: 90
      - name: SCP artifacts to download.eclipse.org to version-specific folder
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1
        with:
          host: projects-storage.eclipse.org
          username: ${{ secrets.SCP_USERNAME }}
          key: ${{ secrets.SCP_KEY }}
          passphrase: ${{ secrets.SCP_PASSPHRASE }}
          source: "repository"
          target: "/home/data/httpd/download.eclipse.org/sailing-analytics/p2/jetty-${{ env.VERSION }}"
          strip_components: 1
          rm: true
