name: release
on:
  push:
    paths:
      - 'wiki/**'
      - '.github/workflows/*'
      - '**/*.md'
      - 'README.md'
      - 'docs/**'
permissions: {}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "No relevant changes --- skipping."
